#!/usr/bin/env node
/*
  Simple build-time generator that reads files in vocab_files/ and creates
  src/generatedVocab.ts exporting a VocabLevel[] compatible with the client.
*/
import fs from "fs";
import path from "path";
import xlsxPackage from "xlsx";

const XLSX = (xlsxPackage.default || xlsxPackage);

const VOCAB_DIR = path.join(process.cwd(), "vocab_files");
const OUT_FILE = path.join(process.cwd(), "src", "generatedVocab.ts");

function normalizeCell(v) {
  if (v === undefined || v === null) return "";
  return String(v).trim();
}

function readFiles() {
  if (!fs.existsSync(VOCAB_DIR)) return [];
  const files = fs.readdirSync(VOCAB_DIR).filter((f) => fs.statSync(path.join(VOCAB_DIR, f)).isFile());
  return files;
}

function parseFile(file) {
  const filePath = path.join(VOCAB_DIR, file);
  try {
    const workbook = XLSX.readFile(filePath);
    const days = {};
    for (const sheetName of workbook.SheetNames) {
      const worksheet = workbook.Sheets[sheetName];
      if (!worksheet) continue;
      const raw = XLSX.utils.sheet_to_json(worksheet, { defval: "" });
      const words = raw.map((row) => {
        const meaning = normalizeCell(row.meaning || row.Meaning || row.translation || "");
        return {
          german_word: normalizeCell(row.german_word || row.German || row['german word'] || ""),
          pronunciation: normalizeCell(row.pronunciation || row.Pronunciation || row.phonetic || ""),
          meaning: meaning,
          example_sentence: normalizeCell(row.example_sentence || row.Example || row.example || ""),
          option_1: normalizeCell(row.option_1 || row.option1 || ""),
          option_2: normalizeCell(row.option_2 || row.option2 || ""),
          option_3: normalizeCell(row.option_3 || row.option3 || ""),
          option_4: normalizeCell(row.option_4 || row.option4 || ""),
          gender: normalizeCell(row.gender || row.Gender || ""),
          emoji: normalizeCell(row.emoji || row.Emoji || ""),
          keyword: normalizeCell(row.keyword || row.Keyword || ""),
          note: normalizeCell(row.note || row.Note || "")
        };
      }).filter((w) => w.german_word && w.meaning);

      if (words.length > 0) {
        let finalName = sheetName.trim();
        if (/^sheet\s*\d+$/i.test(finalName)) {
          const num = finalName.match(/\d+/)?.[0] || "1";
          finalName = `Day ${num}`;
        }
        days[finalName] = words;
      }
    }

    if (Object.keys(days).length === 0) return null;

    const rawName = path.basename(file).replace(/\.[^/.]+$/, "");
    let cleanName = rawName;
    const m = rawName.match(/^(.+?)_vocab$/i);
    if (m) cleanName = m[1].trim();
    else {
      cleanName = rawName.replace(/[_-]/g, " ").trim();
      cleanName = cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
    }

    const id = `folder_${rawName.toLowerCase().replace(/[^a-z0-9]/g, "_")}`;
    return { id, name: cleanName, days };
  } catch (e) {
    console.error(`Failed to parse ${file}:`, e.message || e);
    return null;
  }
}

function generate() {
  const files = readFiles();
  const levels = [];
  for (const f of files) {
    const ext = path.extname(f).toLowerCase();
    if ([".csv", ".xlsx", ".xls", ".ods", ".excel"].includes(ext)) {
      const parsed = parseFile(f);
      if (parsed) levels.push(parsed);
    }
  }

  // Sort by name
  levels.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' }));

  const out = `// Auto-generated by scripts/generate-vocab.js - do not edit by hand\nexport const GENERATED_LEVELS = ${JSON.stringify(levels, null, 2)} as any;\n`;
  // Remove previous generated file if it exists to ensure a clean regenerate
  try {
    if (fs.existsSync(OUT_FILE)) {
      fs.unlinkSync(OUT_FILE);
    }
  } catch (e) {
    // ignore unlink errors
  }

  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log(`Wrote ${OUT_FILE} (${levels.length} levels)`);
}

generate();
